version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "3002:8080"
    volumes:
      - openwebui_data:/app/backend/data
      - ./openwebui-config/openapi_servers.json:/app/backend/data/openapi_servers.json
    environment:
      - WEBUI_NAME=OpenWebUI with MCP
      - WEBUI_AUTH=false
      - OLLAMA_BASE_URL=http://${OLLAMA_SERVER_IP}:11434
      - OPENAI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_BASE_URL=https://generativelanguage.googleapis.com/v1beta/openai
    depends_on:
      - mcpo-server
    networks:
      - webui-network
    restart: unless-stopped

  mcpo-server:
    image: ghcr.io/open-webui/mcpo:main
    container_name: mcpo-server
    ports:
      - "8005:8000"
#    environment:
#      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
    command: [
      "--port", "8000",
#      "--api-key", "top-secret",
      "--config", "/app/config/config.json"
    ]
    volumes:
      - ./mcpo-config:/app/config
    networks:
      - webui-network
    restart: unless-stopped

volumes:
  openwebui_data:

networks:
  webui-network:
    driver: bridge
